foo: bar
spring:
  jackson:
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null
    deserialization:
      READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
      FAIL_ON_UNKNOWN_PROPERTIES: false
  datasource:
    url: jdbc:postgresql://127.0.0.1/demo
    username: jy
    password: 123123

mybatis-plus:
  global-config:
    banner: false
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
  mapper-locations: classpath*:/mappers/*.xml
